
// -*- C++ -*-
// $Id: Version.h 94257 2011-06-23 11:47:48Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define ACE_MAJOR_VERSION 6
#define ACE_MINOR_VERSION 0
#define ACE_BETA_VERSION 3
#define ACE_VERSION "6.0.3"
